#!/usr/bin/env sh

npx lint-staged
# We have to run type checking here because if we run it only on the staged files
# via lint-staged, it will not use our tsconfig and flag all kinds of false positives
# see: https://github.com/microsoft/TypeScript/issues/27379#issuecomment-425245572
npm run type:check