name: prettier

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Run Prettier Check
        run: npx prettier --check .
