name: PR Workflow

on:
  pull_request:
    branches:
      - '**'

jobs:
  Code-Quality-Checks:
    name: Performs linting, formatting, type-checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Count number of lines
        run: |
          chmod +x ./.github/workflows/countline.py
          ./.github/workflows/countline.py --lines 500

      - name: Get changed TypeScript files
        id: changed-files
        uses: tj-actions/changed-files@v40
      
      - name: Check formatting
        if: steps.changed-files.outputs.only_changed != 'true'
        run: npm run format:check

      - name: Check for type errors
        if: steps.changed-files.outputs.only_changed != 'true'
        run: npm run typecheck

      - name: Run linting check
        if: steps.changed-files.outputs.only_changed != 'true'
        run: npm run lint:check
        


  Check-Changed-Files:
    name: File count, sensitive files and branch check
    runs-on: ubuntu-latest
    # needs: Code-Quality-Checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Run Python script
        run: |
          python .github/workflows/count_changed_files.py --base_branch "${{ github.base_ref }}" --pr_branch "${{ github.head_ref }}"

  Check-ESlint-Disable:
    name: Check for eslint-disable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Run Python script
        run: |
          python .github/workflows/eslint_disable_check.py

  Test-Application:
    name: Test Application
    runs-on: ubuntu-latest
    needs: [Code-Quality-Checks]
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install
      
      - name: Get changed TypeScript files
        id: changed-files
        uses: tj-actions/changed-files@v40     
      
      - name: TypeScript compilation for changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_files }}; do
            if [[ "$file" == *.ts || "$file" == *.tsx ]]; then
              npx tsc --noEmit "$file"
            fi
          done
